name: RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update
      run: sudo apt update

    - name: Install Desktop + RDP
      run: |
        sudo apt install xfce4 xfce4-goodies -y
        sudo apt install xrdp -y
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set password
      run: |
        echo "runner:123456" | sudo chpasswd

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        ./ngrok authtoken TOKEN_NGROK_KAMU

    - name: Run ngrok
      run: ./ngrok tcp 3389
