name: RDP No Ngrok

on: [workflow_dispatch]

jobs:
  rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Install Desktop + RDP
      run: |
        sudo apt update
        sudo apt install xfce4 xfce4-goodies -y
        sudo apt install xrdp -y
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set password
      run: echo "runner:123456" | sudo chpasswd

    - name: Install cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Run Tunnel
      run: |
        cloudflared tunnel --no-autoupdate --url tcp://localhost:3389
